const {wb,OUT,short,f2,stores,S,table,title,note,oak,OAKNOTE,FK,GK}=require('./build');const {r2}=require('./model');
const t=f=>r2(S.reduce((a,s)=>a+f(s),0));const by=re=>S.find(s=>re.test(s.loc));
const ws=wb.addWorksheet('Discrepancies',{views:[{state:'frozen',ySplit:4}]});
wb.worksheets.unshift(wb.worksheets.pop());wb.worksheets.forEach((w,i)=>w.orderNo=i);
title(ws,'FARE Grubhub Discrepancies and Proposed Corrections (excl. sales tax)','Amounts from the Summary and supporting tabs. Positive = 1103 overstated at the location. Sales tax is not analyzed.');
const items=[
 ['Jan-Aug fees not booked','Oak Park, Loop, Northwestern',t(s=>s.Cex),'Grubhub fees, marketing, promotions and refunds through 9/21 were '+f2(t(s=>s.feesEx+s.refEx))+'; the Grubhub fee JEs through 9/20 booked '+f2(t(s=>s.feesGLex))+'. September ties, so the gap is all Jan-Aug. Oak Park had no monthly entries ('+f2(by(/Oak Park/).Cex)+'); Loop ('+f2(by(/Loop/).Cex)+') and Northwestern ('+f2(by(/Northwestern/).Cex)+') are short mainly on their catering stores. See Fees by Category and Monthly by Location.','Book the Fee Variance by location and account (table below).'],
 ['8/31 GrubHub AJE is not a deposit reclass','Holding',28283.94,'Jan-Jul Grubhub deposits posted to FARE Holding. The 8/31 AJE credited the stores 133,785.29, about each store\'s whole 8/31 balance, which swept unbooked fees into Holding. Holding 1103 carries 28,283.94, of which '+f2(oak.ajeX)+' came from the credit to Oak Park.','Dr 1103 at each store / Cr 1103 FARE Holding for the AJE Over Reclass column (Sterling and Old Town reverse). Holding goes to zero.'],
 ['Tips not in the DSS clearing debit','All',-t(s=>s.tip),'Grubhub pays tips of '+f2(t(s=>s.tip))+' in the payout, but the DSS debits 1103 without them, so deposits over-clear 1103. Mostly Loop (2,786.02) and Northwestern (1,979.40) catering and self-delivery.','Map the Grubhub tip line in Toast/DSS to 1103, or book tips received to 1103 with the fee JE.'],
 ['Lakeview Grubhub sales with no Grubhub store','Lakeview (W Diversey)',by(/Lakeview/).dssEx,'DSS put Grubhub sales on Lakeview 8/1-9/21 (3,024.37 excl. tax, more after 9/21), but no Lakeview store is in the Grubhub download, and no Lakeview Grubhub deposit exists. A 463.86 fee JE was booked in August with no statement behind it.','Confirm whether Lakeview is on a separate Grubhub account. If yes, pull that statement. If not, the Toast payment type is mis-mapped.'],
 ['Logan Square 3/4 DSS spike','Logan Square',2109.86,'DSS posted about 2,250.66 excl. tax to 1103 on 3/4; Grubhub shows 140.80 that day. No matching Grubhub order at any date.','Check the 3/4 Toast Grubhub payments; likely a catering order from another platform or a duplicate.'],
 ['Old Town DSS about 20% below Grubhub','Old Town',by(/Old Town/).Bex,'Old Town DSS runs about 20% below the Grubhub sales every day since Aug, the pattern of the Toast menu price being used where the Grubhub price is higher.','Check the Old Town Toast Grubhub menu or DSS mapping.'],
 ['Catering timing','Loop, Northwestern',null,'Catering orders post to DSS on the event date while Grubhub dates them when placed. Daily swings net out; see Daily Sales Variances.','None, beyond tips above.'],
 ['Deposit with no Grubhub payout','Northwestern Memorial Hospital',469.85,'BD002858 on 7/17, no comment, matches no Grubhub payout. Every Grubhub payout through 9/25 now ties to a deposit.','Identify the source; reclass if it is not Grubhub.'],
 ['September weekly entries','All',null,'Booked for every store 9/6 through 9/27 and tie to Grubhub for 9/1-9/21 (29.38 total difference, tax on refunds in 7535). The 9/27 entries cover 9/22-9/28 and are netted against the unpaid week.','None.'],
];
let r=table(ws,4,[['Issue','0','t',38],['Location','1','t',26],['Amount','2'],['Detail','3','t',90],['Proposed Fix','4','t',60]],items.map(i=>Object.assign({},i)),{total:false});
for(let i=5;i<r;i++){ws.getRow(i).alignment={wrapText:true,vertical:'top'}}
r+=2;ws.getRow(r).getCell(1).value='Proposed correction by location (excl. sales tax)';ws.getRow(r).font={bold:true,size:12};
const rows=S.map(s=>{const o={loc:short(s.loc)};FK.forEach(([k,fn],i)=>o[k]=r2(fn(s.h)-(s.feeA[GK[i]]||0)));o.fee=s.Cex;o.aje=s.loc==='FARE Holding LLC'?-28283.94:s.ajeX;o.after=r2(s.endEx-s.Cex+o.aje);o.A=s.Aex;o.rest=r2(o.after-s.Aex);return o});
r=table(ws,r+1,[['Location','loc','t',26],...FK.map(([k])=>['Book '+k,k]),['Fee JE (Cr 1103)','fee'],['AJE Fix (Dr / (Cr) 1103)','aje'],['1103 excl. Tax After Fixes','after'],['  Unpaid Week 9/22-9/30','A'],['  Remaining Sales Variance','rest']],rows);
note(ws,r+1,'1103 After Fixes = 1103 excl. sales tax less the fee JE plus the AJE fix. What remains is the unpaid week plus the sales variances above (tips, Lakeview, Logan 3/4, Old Town, the Northwestern deposit).');
wb.xlsx.writeFile(OUT).then(()=>console.log('wrote',OUT));
