const fs=require('fs');let s;const rep=(a,b)=>{if(!s.includes(a))throw new Error('missing: '+a.slice(0,90));s=s.split(a).join(b)};
s=fs.readFileSync('build.js','utf8');
rep("['  Sept deductions not yet booked','Csep']","['  Week of 9/21-9/27 not yet booked','Csep']");
rep("['  Payouts with no 1102 deposit','undep']","['  Payout deposited outside 1102','undep']");
rep(",undepAll=up.filter(p=>p.date>='2026-09-01'),nmh=",",nmh=");
rep("const u17=undepAll.filter(p=>p.date==='2026-09-17'),u24=undepAll.filter(p=>p.date==='2026-09-24');\n","const lvDup=150.33;\n");
s=s.replace(/ \['High','All stores','DSS leaves sales tax in 1102',totT,`[^`]*`/,` ['High','All stores','DSS leaves sales tax in 1102',totT,\`The DSS debits 1102 with each DoorDash order's sales tax included. DoorDash remits that tax itself and never pays it to FARE, and the DoorDash fee entries keep tax off, so it builds up in 1102 every week. This is a DSS / POS setup issue rather than a fee entry issue.\``);
s=s.replace(/ \['Medium','9 stores','Payouts with no deposit in R365'[^\n]*\n/,` ['Medium','Lakeview','Week of 9/20 DoorDash fee entry booked twice',lvDup,'Two DoorDash entries dated 9/20/26 at Lakeview each credit 1102 150.33. DoorDash deductions for the week of 9/14-9/20 are 150.33. Every other September week ties to DoorDash to the penny at every store.','Delete or reverse one of the two 9/20 Lakeview DoorDash entries.'],\n`);
s=s.replace(/ \['Medium','All stores','September DoorDash fees not booked yet'[^\n]*\n/,` ['Info','All stores','Week of 9/21-9/27 fees not booked yet',totSep,'DoorDash pays the week of 9/21-9/27 on 10/1, so its entry is not due yet. The 9/6, 9/13 and 9/20 weekly entries are posted and tie.','Post with the 10/1 payout.'],\n`);
rep("'After JE 1-2, each store 1102 balance equals: sales variance + other fee variance + Sept fees (unbooked) + net not yet deposited + sales tax left in 1102 (Summary tab).'","'After JE 1-2 and removing the Lakeview duplicate, each store 1102 balance equals: sales variance + other fee variance + week of 9/21 fees (not due yet) + 9/21-9/27 net not yet paid + sales tax left in 1102 (Summary tab).'");
rep("module.exports={F,S,FL,drv,H,totT,taxJA,taxSep,totSep,u17,u24,nmh,je1,je2,mf};","module.exports={F,S,FL,drv,H,totT,totSep,nmh,je1,je2,mf};");
rep("GL from the monthly DoorDash JEs (Jan-Aug), so the Variance column includes Sept.","GL from the monthly DoorDash JEs (Jan-Aug) and weekly entries (Sept), so the Variance column includes the week of 9/21-9/27, not booked yet.");
fs.writeFileSync('build.js',s);
s=fs.readFileSync('report.js','utf8');
rep("['Sept Fees Unbooked','Csep']","['Wk 9/21 Fees Unbooked','Csep']");
rep("DoorDash money not yet deposited: 9/21-9/27 activity not yet paid out (${f(T('unpaid'))}), payouts with no 1102 deposit (${f(T('undep'))}), less","DoorDash money not yet in 1102 deposits: 9/21-9/27 activity DoorDash pays on 10/1 (${f(T('unpaid'))}), the NMH 7/16 payout deposited to Grubhub clearing (${f(T('undep'))}), less");
rep("<li><b>${f(b.totSep)}</b> September DoorDash fees not booked yet, plus <b>${f(r2(T('Cother')))}</b> of other fee differences.</li>","<li><b>${f(b.totSep)}</b> fees for the week of 9/21-9/27, not due until the 10/1 payout, plus <b>${f(r2(T('Cother')))}</b> of other fee differences (mostly the duplicate Lakeview 9/20 entry).</li>");
rep("<th>GL Booked</th><th>Unbooked (mostly Sept)</th>","<th>GL Booked</th><th>Unbooked (mostly wk of 9/21)</th>");
fs.writeFileSync('report.js',s);console.log('ok');
